name: Bug report
description: Report a reproducible problem to help us improve
labels: ["bug", "needs-triage"]
title: "bug: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-checks
      options:
        - label: I have searched existing issues to ensure this hasn't been reported already.
          required: true
        - label: I have read the README, CONTRIBUTING.md, and relevant docs.
          required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project is affected?
      options:
        - Tools (CKM, Terminology, Specs)
        - Prompts (Explorers, Designers, etc.)
        - Resources (Guides, BMM, etc.)
        - Infrastructure (Docker, PHP, Makefile)
        - Other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package/version
      description: What version/commit are you using? (e.g., git SHA or tag)
      placeholder: vX.Y.Z or commit SHA
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Any relevant environment details
      placeholder: |
        - MCP client/host: Claude, Cursor, LibreChat, etc
        - Environment: Cadasto/local/Docker
        - Transport: streamable-http/stdio
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: Describe the bug and the expected vs actual behavior
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide a minimal set of steps or code to reproduce the issue
      placeholder: |
        1. Go to ...
        2. Run command ...
        3. See error ...
  - type: textarea
    id: logs
    attributes:
      label: Logs and stack traces
      description: Paste relevant logs, error output, or stack traces. Set LOG_LEVEL=debug for more info.
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, links to related issues/PRs, screenshots
